version: "3.9"
services:
  calcureact:
    build:
      context: ./calculadora
      dockerfile: Dockerfile
    container_name: estuardosonu_frontend_practica1_202003894
    ports:
      - "3000:3000"

  calcudb:
    build:
      context: ./DBCalculadora
      dockerfile: Dockerfile
    container_name: estuardosonu_basedatos_practica1_202003894
    environment:
      MYSQL_DATABASE: "DBCalculadora"
      MYSQL_USER: 'estuardo'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./DBCalculadora/operaciones:/var/lib/mysql
    ports:
      - "3307:3306"
    
  calcugo:
    build:
      context: ./BackCalculadora
      dockerfile: Dockerfile
    container_name: estuardosonu_backend_practica1_202003894
    ports:
      - "8080:8080"
    expose:
      - "8080"

volumes:
  operaciones: {}