version: "3.9"
services:
  calcudb:
    build:
      context: ./DBCalculadora
      dockerfile: Dockerfile
    container_name: database
    environment:
      MYSQL_DATABASE: "DBCalculadora"
      MYSQL_USER: 'estuardo'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./DBCalculadora/operaciones:/var/lib/mysql
    networks:
      - practica1-so1
    ports:
      - "3307:3306"
    
  calcugo:
    build:
      context: ./BackCalculadora
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - practica1-so1
    depends_on:
      - calcudb
  
  calcureact:
    build:
      context: ./calculadora
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - practica1-so1
    depends_on:
      - calcudb
      - calcugo

volumes:
  operaciones: {}

networks:
  practica1-so1: